language: scala
services:
  - cassandra
scala:
  - 2.11.7

notifications:
  slack: uw-cse:NkMpzlqTOyAGlT6jMIfgZ8w3

jdk:
  - oraclejdk8

install:
  - git clone https://github.com/bholt/phantom.git /tmp/phantom
  - cd /tmp/phantom && sbt ++$TRAVIS_SCALA_VERSION publishLocal

before_script: travis_retry sbt ++$TRAVIS_SCALA_VERSION update

script:
  - cqlsh --file=keyspace.cql
  - sbt ++$TRAVIS_SCALA_VERSION test -Dcassandra.host.0=127.0.0.1
