version: '2'

services:

  owl:
    image: bholt/owl
    command: tail -f /dev/null
    privileged: true
    networks:
      - dev
    environment:
      CASSANDRA_HOST: owl_cass_1
    #   - "constraint:node==ibex"
    cpu_shares: 6

  cass:
    image: bholt/cassandra
    command: cassandra -f
    environment:
      JVM_OPTS: -Dcassandra.consistent.rangemovement=false
      CASSANDRA_SEEDS: owl_cass_1
    privileged: true
    networks:
      - dev
    cpu_shares: 2

networks:
  dev:
    driver: overlay
